/*
 * This source file was generated by the Gradle 'init' task
 */
package dev250331;

import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);

        new App(sc).run();

        sc.close();
    }
}
